"""
Base strategy class that all trading strategies inherit from.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Optional

import pandas as pd


class SignalType(Enum):
    """Trading signal types."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    """
    symbol: str
    signal_type: SignalType
    confidence: float  # 0.0 to 1.0
    price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reason: str = ""

    @property
    def is_actionable(self) -> bool:
        """Check if signal is buy or sell (not hold)."""
        return self.signal_type != SignalType.HOLD

    def __str__(self) -> str:
        price_str = f"{self.price:.2f}" if self.price else "market"
        return (
            f"Signal({self.symbol}: {self.signal_type.value} "
            f"@ {price_str}, "
            f"confidence={self.confidence:.2%})"
        )


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must implement the `generate_signal` method.
    """

    def __init__(self, name: str, weight: float = 1.0):
        """
        Initialize the strategy.

        Args:
            name: Strategy identifier
            weight: Weight for combining with other strategies (0.0 to 1.0)
        """
        self.name = name
        self.weight = weight
        self._is_trained = False

    @abstractmethod
    def generate_signal(self, symbol: str, data: pd.DataFrame) -> Signal:
        """
        Generate a trading signal for the given symbol.

        Args:
            symbol: Ticker symbol
            data: Historical price data with indicators

        Returns:
            Signal object with recommendation
        """
        pass

    def train(self, data: pd.DataFrame) -> None:
        """
        Train the strategy on historical data (optional).

        Override this method for ML-based strategies.
        """
        self._is_trained = True

    @property
    def is_trained(self) -> bool:
        """Check if strategy has been trained."""
        return self._is_trained

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}', weight={self.weight})"
